/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Audition } from "./Audition";
import { AuditionCountArgs } from "./AuditionCountArgs";
import { AuditionFindManyArgs } from "./AuditionFindManyArgs";
import { AuditionFindUniqueArgs } from "./AuditionFindUniqueArgs";
import { DeleteAuditionArgs } from "./DeleteAuditionArgs";
import { AuditionService } from "../audition.service";
@graphql.Resolver(() => Audition)
export class AuditionResolverBase {
  constructor(protected readonly service: AuditionService) {}

  async _auditionsMeta(
    @graphql.Args() args: AuditionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Audition])
  async auditions(
    @graphql.Args() args: AuditionFindManyArgs
  ): Promise<Audition[]> {
    return this.service.auditions(args);
  }

  @graphql.Query(() => Audition, { nullable: true })
  async audition(
    @graphql.Args() args: AuditionFindUniqueArgs
  ): Promise<Audition | null> {
    const result = await this.service.audition(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Audition)
  async deleteAudition(
    @graphql.Args() args: DeleteAuditionArgs
  ): Promise<Audition | null> {
    try {
      return await this.service.deleteAudition(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
