/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Actor } from "./Actor";
import { ActorCountArgs } from "./ActorCountArgs";
import { ActorFindManyArgs } from "./ActorFindManyArgs";
import { ActorFindUniqueArgs } from "./ActorFindUniqueArgs";
import { DeleteActorArgs } from "./DeleteActorArgs";
import { ActorService } from "../actor.service";
@graphql.Resolver(() => Actor)
export class ActorResolverBase {
  constructor(protected readonly service: ActorService) {}

  async _actorsMeta(
    @graphql.Args() args: ActorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Actor])
  async actors(@graphql.Args() args: ActorFindManyArgs): Promise<Actor[]> {
    return this.service.actors(args);
  }

  @graphql.Query(() => Actor, { nullable: true })
  async actor(
    @graphql.Args() args: ActorFindUniqueArgs
  ): Promise<Actor | null> {
    const result = await this.service.actor(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Actor)
  async deleteActor(
    @graphql.Args() args: DeleteActorArgs
  ): Promise<Actor | null> {
    try {
      return await this.service.deleteActor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
